#This is a phusion/baseimage:0.11 Image
FROM phusion/baseimage:0.11
MAINTAINER rashbits@gmail.com

# Installing dependencies and java version 8
RUN apt-get update

# Running echo command cat >> /etc/environment <<EOL
#CMD ["echo",  "cat >> /etc/environment <<EOL"]

# Making directory /var/datanext
#RUN mkdir /var/DataFlowService

# Copying file from target folder to above created folder
#COPY ./DataFlowService /var/DataFlowService

#Downloading flink
#WORKDIR /var



